/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jewelry_management_system.dashboard;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Harihara sudhan
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLocation(510, 200);
        JLabel appNameLabel = new JLabel();
        appNameLabel.setForeground(new Color(2, 190, 255));
        appNameLabel.setBackground(new java.awt.Color(171, 225, 245));
        myAccountBtn = new javax.swing.JButton();
        JTabbedPane contentHolder = new JTabbedPane();
        JScrollPane homeTab = new JScrollPane();
        homeTab.setBackground(new java.awt.Color(171, 225, 245));
        JPanel addJewelTab = new JPanel();
        addJewelTab.setBackground(new java.awt.Color(171, 225, 245));
        JPanel orderPlaceTab = new JPanel();
        orderPlaceTab.setBackground(new java.awt.Color(171, 225, 245));
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        appNameLabel.setFont(new java.awt.Font("Serif", Font.BOLD, 24)); // NOI18N
        appNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appNameLabel.setText("Jewelry Management System");
        myAccountBtn.setFont(new java.awt.Font("Serif", Font.PLAIN, 18));// NOI18N
        myAccountBtn.setForeground(new Color(37, 195, 250));
        myAccountBtn.setText("My Account");
        myAccountBtn.setMaximumSize(new java.awt.Dimension(599, 521));
        myAccountBtn.setMinimumSize(new java.awt.Dimension(599, 521));
        myAccountBtn.addActionListener(this::myAccountBtnActionPerformed);

        contentHolder.addTab("Home", homeTab);

        javax.swing.GroupLayout addJewelTabLayout = new javax.swing.GroupLayout(addJewelTab);
        addJewelTab.setLayout(addJewelTabLayout);
        addJewelTabLayout.setHorizontalGroup(
            addJewelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        addJewelTabLayout.setVerticalGroup(
            addJewelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        contentHolder.addTab("Add Jewel", addJewelTab);

        javax.swing.GroupLayout orderPlaceTabLayout = new javax.swing.GroupLayout(orderPlaceTab);
        orderPlaceTab.setLayout(orderPlaceTabLayout);
        orderPlaceTabLayout.setHorizontalGroup(
            orderPlaceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        orderPlaceTabLayout.setVerticalGroup(
            orderPlaceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        contentHolder.addTab("Place Order", orderPlaceTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(myAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addComponent(contentHolder)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccountBtnActionPerformed
        // TODO add your handling code here:
        Point point = myAccountBtn.getLocation();
        MyAccountPopup popup = new MyAccountPopup(this, point);
        popup.show();
    }//GEN-LAST:event_myAccountBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton myAccountBtn;
    // End of variables declaration//GEN-END:variables
}
