/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jewelry_management_system.login;

import jewelry_management_system.db.DBHelper;
import jewelry_management_system.session.SessionManager;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/**
 *
 * @author MYPC
 */
public class ChangeUserName extends javax.swing.JDialog {

    /**
     * Creates new form ChangeUserName
     */
    String oldUsername ="";
    String newUsername ="";
    String password="";
    private final DBHelper helper;
    public ChangeUserName(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        helper = DBHelper.getDBHelperInstance();
        //helper = DBHelper.getDBHelperInstance("root", "root");
        initComponents();
        setLocation(650,250);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel jLabel3 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JLabel usernamePromptLabel = new JLabel();
        JLabel newUsernamePromptLabel = new JLabel();
        JLabel passwordPromptLabel = new JLabel();
        txtNewUsername = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        JButton changeUsernameBtn = new JButton();
        txtPassword = new javax.swing.JPasswordField();
        oldUsernameErrMsg = new javax.swing.JLabel();
        newUsernameErrMsg = new javax.swing.JLabel();
        passwordErrMsg = new javax.swing.JLabel();

        jLabel3.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Username");
        setResizable(false);

        usernamePromptLabel.setFont(new java.awt.Font("Serif", Font.BOLD, 18)); // NOI18N
        usernamePromptLabel.setForeground(new java.awt.Color(0, 0, 255));
        usernamePromptLabel.setText("Username");

        newUsernamePromptLabel.setFont(new java.awt.Font("Serif", Font.BOLD, 18)); // NOI18N
        newUsernamePromptLabel.setForeground(new java.awt.Color(0, 0, 255));
        newUsernamePromptLabel.setText("New Username");

        passwordPromptLabel.setFont(new java.awt.Font("Serif", Font.BOLD, 18)); // NOI18N
        passwordPromptLabel.setForeground(new java.awt.Color(0, 0, 255));
        passwordPromptLabel.setText("Password");

        txtNewUsername.setFont(new java.awt.Font("Serif", Font.PLAIN, 14)); // NOI18N
        txtNewUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewUsernameFocusGained();
            }
        });
        txtUsername.setFont(new java.awt.Font("Serif", Font.PLAIN, 14)); // NOI18N
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained();
            }
        });
        changeUsernameBtn.setFont(new java.awt.Font("Serif", Font.BOLD, 18)); // NOI18N
        changeUsernameBtn.setForeground(new java.awt.Color(0, 0, 255));
        changeUsernameBtn.setText("Change Username");
        changeUsernameBtn.addActionListener(this::changeUsernameBtnActionPerformed);

        txtPassword.setFont(new java.awt.Font("Serif", Font.PLAIN, 14)); // NOI18N
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained();
            }
        });

        oldUsernameErrMsg.setFont(new java.awt.Font("Serif", Font.PLAIN, 14)); // NOI18N
        oldUsernameErrMsg.setForeground(new java.awt.Color(255, 0, 0));

        newUsernameErrMsg.setFont(new java.awt.Font("Serif", Font.PLAIN, 14)); // NOI18N
        newUsernameErrMsg.setForeground(new java.awt.Color(255, 0, 0));

        passwordErrMsg.setFont(new java.awt.Font("Serif", Font.PLAIN, 14)); // NOI18N
        passwordErrMsg.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(changeUsernameBtn)
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordErrMsg)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPassword)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNewUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                .addComponent(usernamePromptLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsername))
                            .addComponent(newUsernamePromptLabel)))
                    .addComponent(oldUsernameErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newUsernameErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(usernamePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(oldUsernameErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newUsernamePromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(newUsernameErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordErrMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(changeUsernameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeUsernameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernameBtnActionPerformed
        oldUsername = txtUsername.getText();
        newUsername = txtNewUsername.getText();
        password = new String(txtPassword.getPassword());
        if(!Objects.equals(oldUsername, "") && !Objects.equals(newUsername, "") && !password.equals("")){
            if(Objects.equals(oldUsername, SessionManager.getCurrentSession().getUsername())) {
                if (!Objects.equals(oldUsername, newUsername)) {
                    if (helper.verifyPassword(password)) {
                        if (helper.updateUsername(newUsername)) {
                            SessionManager.getCurrentSession().setUsername(newUsername);
                            SessionManager.storeCurrentSession();
                            JOptionPane.showMessageDialog(this, "Username updated successfully");
                            dispose();
                        }
                    } else {
                        passwordErrMsg.setText("Incorrect password");
                    }
                } else {
                    newUsernameErrMsg.setText("New username can't be same as old one");
                }
            }else{
                oldUsernameErrMsg.setText("Incorrect username");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Kindly enter all the details");
        }

    }//GEN-LAST:event_changeUsernameBtnActionPerformed

    private void txtUsernameFocusGained() {//GEN-FIRST:event_txtUsernameFocusGained
        clearErrorMessage();
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtNewUsernameFocusGained() {//GEN-FIRST:event_txtNewUsernameFocusGained
        clearErrorMessage();
    }//GEN-LAST:event_txtNewUsernameFocusGained

    private void txtPasswordFocusGained() {//GEN-FIRST:event_txtPasswordFocusGained
        clearErrorMessage();
    }//GEN-LAST:event_txtPasswordFocusGained

    private void clearErrorMessage(){
        oldUsernameErrMsg.setText("");
        newUsernameErrMsg.setText("");
        passwordErrMsg.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ChangeUserName dialog = new ChangeUserName(new JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel newUsernameErrMsg;
    private javax.swing.JLabel oldUsernameErrMsg;
    private javax.swing.JLabel passwordErrMsg;
    private javax.swing.JTextField txtNewUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
