/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jewelry_management_system.login;

import jewelry_management_system.DBHandler;
import jewelry_management_system.Dashboard;
import jewelry_management_system.db.DBHelper;
import jewelry_management_system.session.Session;
import jewelry_management_system.session.SessionManager;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MYPC
 */
public class Login extends javax.swing.JFrame {
    //database manager credentials
    String app_mngr_user = "root";
    String app_mngr_pass = "root";
    private final DBHelper dbHelper;

    /**
     * Creates new form Login
     */
    public Login() {
        setLocationRelativeTo(null);
        setExtendedState(getExtendedState() | JFrame.NORMAL);
        initComponents();
        dbHelper = DBHelper.getDBHelperInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel uNameLabel = new JLabel();
        JLabel pWordLabel = new JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton btnLogin = new JButton();
        JLabel heading = new JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(171, 225, 245));
        setLocation(new java.awt.Point(810, 340));
        uNameLabel.setText("User Name");
        pWordLabel.setText("Password");
        pWordLabel.setFont(new Font("Serif", Font.BOLD, 15));
        uNameLabel.setFont(new Font("Serif", Font.BOLD, 15));
        uNameLabel.setForeground(new Color(2, 190, 255));
        pWordLabel.setForeground(new Color(2, 190, 255));
        txtUsername.setFont(new java.awt.Font("Serif", Font.PLAIN, 13)); // NOI18N
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.setName("");
        txtUsername.grabFocus();
        txtUsername.transferFocusDownCycle();
        txtPassword.setMinimumSize(new java.awt.Dimension(6, 25));
        txtPassword.setPreferredSize(new java.awt.Dimension(6, 25));
        btnLogin.setText("Login");
        btnLogin.setForeground(new Color(0, 0, 0));
        btnLogin.setBackground(new Color(171, 225, 245));
        btnLogin.addActionListener(this::loginBtnPressed);
        heading.setForeground(new java.awt.Color(2, 190, 255));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Login to continue");
        heading.setVerifyInputWhenFocusTarget(false);
        heading.setFont(new Font("Serif", Font.BOLD, 25));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addComponent(txtUsername)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnLogin)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //GEN-LAST:event_t_passwordActionPerformed

    private void loginBtnPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        // TODO add your handling code here:
        String name = txtUsername.getText();
        String pass = new String(txtPassword.getPassword());
        boolean visibility=false;
        if(name.isEmpty() || pass.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Enter User Name and Password");	//prompting for username and password
            return;
        }
        try {
            DBHandler dbh = new DBHandler(app_mngr_user,app_mngr_pass);
            visibility = dbHelper.verifyUser(name, pass);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(visibility)
        {
            System.out.println("logged in successfully");
            setVisible(false);
            SessionManager.CreateNewSession(name);
            SessionManager.storeCurrentSession();
            new Dashboard().setVisible(true);
        }
        else
            javax.swing.JOptionPane.showMessageDialog(null,"Invalid Username and Password");
    }//GEN-LAST:event_b_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        Session session = SessionManager.loadSession();
        if(session == null) {
            java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
        }else{
            new Dashboard().setVisible(true);
        }
    }

    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
