/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jewelry_management_system.login;

import jewelry_management_system.dashboard.Dashboard;
import jewelry_management_system.db.DBHelper;
import jewelry_management_system.session.Session;
import jewelry_management_system.session.SessionManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author Harihara sudhan
 */
public class Login extends javax.swing.JFrame {

    private final DBHelper helper;
    public Login() {
        helper = DBHelper.getDBHelperInstance();
        //helper = DBHelper.getDBHelperInstance("root", "root");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel appNameLabel = new JLabel();
        JPanel jPanel1 = new JPanel();
        txtUsername = new javax.swing.JTextField();
        JLabel usernamePromptLabel = new JLabel();
        JLabel passwordPromptLabel = new JLabel();
        JButton continueBtn = new JButton();
        txtPassword = new javax.swing.JPasswordField();
        usernameErrMsg = new javax.swing.JLabel();
        passwordErrMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        appNameLabel.setFont(new java.awt.Font("Serif", Font.BOLD, 24)); // NOI18N
        appNameLabel.setForeground(new java.awt.Color(0, 0, 204));
        appNameLabel.setText("Jewelry management system");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 204), new java.awt.Color(0, 0, 204), new java.awt.Color(0, 0, 204), new java.awt.Color(0, 0, 204)));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        txtUsername.setFont(new java.awt.Font("Serif", Font.PLAIN, 18)); // NOI18N
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained();
            }
        });
        txtUsername.addActionListener(evt -> txtUsernameActionPerformed());

        usernamePromptLabel.setFont(new java.awt.Font("Serif", Font.PLAIN, 18)); // NOI18N
        usernamePromptLabel.setForeground(new java.awt.Color(0, 0, 204));
        usernamePromptLabel.setText("Username");

        passwordPromptLabel.setFont(new java.awt.Font("Serif", Font.PLAIN, 18)); // NOI18N
        passwordPromptLabel.setForeground(new java.awt.Color(0, 0, 204));
        passwordPromptLabel.setText("Password");

        continueBtn.setFont(new java.awt.Font("Serif", Font.PLAIN, 18)); // NOI18N
        continueBtn.setForeground(new java.awt.Color(0, 0, 204));
        continueBtn.setText("Continue");
        continueBtn.addActionListener(evt -> continueBtnActionPerformed());

        txtPassword.setFont(new java.awt.Font("Serif", Font.PLAIN, 18)); // NOI18N
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained();
            }
        });
        txtPassword.addActionListener(evt -> txtPasswordActionPerformed());
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        usernameErrMsg.setFont(new java.awt.Font("Serif", Font.PLAIN, 14)); // NOI18N
        usernameErrMsg.setForeground(new java.awt.Color(255, 0, 0));

        passwordErrMsg.setFont(new java.awt.Font("Serif", Font.PLAIN, 14)); // NOI18N
        passwordErrMsg.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                        .addComponent(passwordPromptLabel)
                        .addComponent(usernamePromptLabel)
                        .addComponent(txtUsername)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(usernamePromptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(passwordPromptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(appNameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(appNameLabel)
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed() {//GEN-FIRST:event_txtPasswordActionPerformed
        clearErrorMessage();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed() {//GEN-FIRST:event_txtUsernameActionPerformed
        clearErrorMessage();
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void continueBtnActionPerformed() {//GEN-FIRST:event_continueBtnActionPerformed
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());
        if(helper.isUserExists(username)){
            if(helper.verifyUser(username, password)){
                SessionManager.CreateNewSession(username);
                SessionManager.storeCurrentSession();
                new Dashboard().setVisible(true);
                dispose();
            }else{
                passwordErrMsg.setText("Incorrect password");
            }
        }else{
            usernameErrMsg.setText("No user associated with this username");
        }
    }//GEN-LAST:event_continueBtnActionPerformed

    private void txtPasswordFocusGained() {//GEN-FIRST:event_txtPasswordFocusGained
        clearErrorMessage();
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsernameFocusGained() {//GEN-FIRST:event_txtUsernameFocusGained
        clearErrorMessage();
    }//GEN-LAST:event_txtUsernameFocusGained

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            continueBtnActionPerformed();
        }
    }//GEN-LAST:event_jPanel1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            continueBtnActionPerformed();
        }
    }//GEN-LAST:event_formKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            continueBtnActionPerformed();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void clearErrorMessage(){
        usernameErrMsg.setText("");
        passwordErrMsg.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Session session = SessionManager.loadSession();
        if(session == null) {
            java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
        }else{
            new Dashboard().setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel passwordErrMsg;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel usernameErrMsg;
    // End of variables declaration//GEN-END:variables
}
